import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Contact(),
        ]),
      ),
    );
  }
}

class Contact extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 430,
                  height: 932,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/images/car.png"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 862,
                child: Container(
                  width: 430,
                  height: 70,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 430,
                          height: 70,
                          decoration: BoxDecoration(
                            color: Color(0x994399FF),
                            border: Border(
                              left: BorderSide(),
                              top: BorderSide(width: 1),
                              right: BorderSide(),
                              bottom: BorderSide(),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 368,
                        top: 15,
                        child: Container(
                          width: 40,
                          height: 40,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: FlutterLogo(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 430,
                  height: 117,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 430,
                          height: 117,
                          decoration: BoxDecoration(
                            color: Color(0x7F4399FF),
                            border: Border(
                              left: BorderSide(),
                              top: BorderSide(width: 1),
                              right: BorderSide(),
                              bottom: BorderSide(width: 1),
                            ),
                            boxShadow: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 61,
                        top: 38,
                        child: Container(
                          width: 307,
                          height: 71,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: AssetImage("assets/images/contact_us.png"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 9,
                top: 146,
                child: Container(
                  width: 411,
                  height: 687.77,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 411,
                          height: 687.77,
                          decoration: ShapeDecoration(
                            color: Color(0x7F4C4646),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(15),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 85,
                        top: 635,
                        child: Container(
                          width: 241,
                          height: 43.81,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 241,
                                  height: 43.81,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFF4399FF),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 52,
                                top: 7.13,
                                child: SizedBox(
                                  width: 138,
                                  height: 30.57,
                                  child: Text(
                                    'send message',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 20,
                                      fontFamily: 'Signika Negative SC',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 35,
                        top: 411.20,
                        child: Container(
                          width: 341,
                          height: 206.84,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 341,
                                  height: 206.84,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 1, color: Color(0xFF4466FF)),
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x3F000000),
                                        blurRadius: 4,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 13,
                                top: 11.21,
                                child: Container(
                                  width: 24,
                                  height: 24.45,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                  ),
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 42,
                                top: 11.21,
                                child: SizedBox(
                                  width: 99,
                                  height: 19.36,
                                  child: Text(
                                    'message',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFF979696),
                                      fontSize: 20,
                                      fontFamily: 'Signika Negative SC',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 119,
                        top: 9.17,
                        child: SizedBox(
                          width: 174,
                          height: 54,
                          child: Text(
                            'Contact US',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 32,
                              fontFamily: 'Signika Negative SC',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 9,
                        top: 53.52,
                        child: Container(
                          width: 394,
                          height: 209.11,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/394x209"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 35,
                        top: 278,
                        child: Container(
                          width: 341,
                          height: 48.91,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 341,
                                  height: 48.91,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 1, color: Color(0xFF4466FF)),
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x3F000000),
                                        blurRadius: 4,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 13,
                                top: 12.23,
                                child: Container(
                                  width: 24,
                                  height: 24.45,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                  ),
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 33,
                                top: 12.23,
                                child: SizedBox(
                                  width: 108,
                                  height: 24.45,
                                  child: Text(
                                    'name',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFF888181),
                                      fontSize: 20,
                                      fontFamily: 'Signika Negative SC',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 35,
                        top: 343.80,
                        child: Container(
                          width: 341,
                          height: 48.91,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 341,
                                  height: 48.91,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 1, color: Color(0xFF4466FF)),
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x3F000000),
                                        blurRadius: 4,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 33,
                                top: 12.23,
                                child: SizedBox(
                                  width: 108,
                                  height: 24.45,
                                  child: Text(
                                    'email',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFF888181),
                                      fontSize: 20,
                                      fontFamily: 'Signika Negative SC',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 13,
                                top: 12.23,
                                child: Container(
                                  width: 24,
                                  height: 24.45,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                  ),
                                  child: FlutterLogo(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}